[tool.poetry]
name = "cast-labeler"
version = "0.1.0"
description = ""
authors = ["Marcelo Morales <morales.374@osu.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
argparse = "^1.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
